/arm_master:
  ros__parameters:
    arm_can_id: can0
    arm_control_type: normal
    arm_pub_topic_name: arm_master_status
    arm_sub_topic_name: arm_master_cmd
    arm_end_type: 1

/arm_follow:
  ros__parameters:
    arm_can_id: can1
    arm_control_type: normal
    arm_pub_topic_name: arm_follow_status
    arm_sub_topic_name: arm_follow_cmd
    arm_end_type: 0